// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns true if patch is downloaded, false if no patch is available
Future<bool> downloadPatch({
  required String serverUrl,
  required String appId,
  required String channel,
  required String currentVersion,
  required String architecture,
  required String platform,
  required String downloadPath,
}) => RustLib.instance.api.crateApiPatchDownloadPatch(
  serverUrl: serverUrl,
  appId: appId,
  channel: channel,
  currentVersion: currentVersion,
  architecture: architecture,
  platform: platform,
  downloadPath: downloadPath,
);

Future<void> applyPatch({
  required String patchFilePath,
  required String initialVersionFilePath,
  required String finalVersionFilePath,
}) => RustLib.instance.api.crateApiPatchApplyPatch(
  patchFilePath: patchFilePath,
  initialVersionFilePath: initialVersionFilePath,
  finalVersionFilePath: finalVersionFilePath,
);
